apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerized-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockerized-app
  template:
    metadata:
      labels:
        app: dockerized-app
    spec:
      containers:
        - name: dockerized-app
          image: bosofisan/dockerized-app-ci:latest
          ports:
            - containerPort: 3000
