apiVersion: v1
kind: Service
metadata:
  name: dockerized-app-service
spec:
  type: NodePort
  selector:
    app: dockerized-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30080
